# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Matt Paulin
email: mattpaulin.com@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Matt Paulin, I have created companies, developed software, and launched products for 20 years.
avatar: /assets/images/cartoonmatt.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  paulin

# Build settings
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-remote-theme

background_image_url: /assets/images/background2.jpeg
porthole_background_image_url: /assets/images/background2.jpeg
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github: [metadata]

# Navigation
header_pages:
  - about.markdown

# Beautiful Jekyll navigation
navbar-links:
  Work: "/portfolio/"
  Carbot: "/categories/carbot/"
  Ideas: "/categories/ideas/"
  "Data Science": "/categories/data/"
  "Product Playbook": "/categories/product_management/"

# Beautiful Jekyll settings
show-avatar: true
show-social-icons: true
show-aboutme: true
show-footer: false
show-date: false

# Social media links
social-links:
  github: paulin
  linkedin: mattpaulin
  email: mattpaulin.com@gmail.com

# Custom CSS
css:
  - /assets/css/beautiful-custom.css